spring:
  application.name: ms-client
  main.banner-mode: off

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: ${PORT:0}
